# Generated by Django 4.0.6 on 2022-07-12 19:48

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_select_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(default='nothing'),
            preserve_default=False,
        ),
    ]
